In [1]:
import numpy as np
import torch

In [2]:
x = torch.rand(3, 2)
x

tensor([[0.0137, 0.8304],
        [0.1892, 0.9249],
        [0.7905, 0.4639]])

In [3]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
y = torch.ones_like(x)
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
z = x + y
z

tensor([[1.0137, 1.8304],
        [1.1892, 1.9249],
        [1.7905, 1.4639]])

In [6]:
z[0]

tensor([1.0137, 1.8304])

In [7]:
z[:, 1:]

tensor([[1.8304],
        [1.9249],
        [1.4639]])

In [8]:
# New tensor
z.add(1)

tensor([[2.0137, 2.8304],
        [2.1892, 2.9249],
        [2.7905, 2.4639]])

In [9]:
# Z is unchanged
z

tensor([[1.0137, 1.8304],
        [1.1892, 1.9249],
        [1.7905, 1.4639]])

In [10]:
z.add_(1)  # In place

tensor([[2.0137, 2.8304],
        [2.1892, 2.9249],
        [2.7905, 2.4639]])

In [11]:
z

tensor([[2.0137, 2.8304],
        [2.1892, 2.9249],
        [2.7905, 2.4639]])

In [12]:
z.size()

torch.Size([3, 2])

Operations followed by a `_` are performed in place.

In [13]:
z.resize_(2, 3)

tensor([[2.0137, 2.8304, 2.1892],
        [2.9249, 2.7905, 2.4639]])

In [14]:
z

tensor([[2.0137, 2.8304, 2.1892],
        [2.9249, 2.7905, 2.4639]])

In [15]:
a = np.random.rand(4, 3)
a

array([[ 0.1197014 ,  0.91228921,  0.44424811],
       [ 0.26773994,  0.72341773,  0.91357858],
       [ 0.24956934,  0.03453914,  0.37598281],
       [ 0.98721395,  0.33306043,  0.04228135]])

In [16]:
b = torch.from_numpy(a)
b

tensor([[0.1197, 0.9123, 0.4442],
        [0.2677, 0.7234, 0.9136],
        [0.2496, 0.0345, 0.3760],
        [0.9872, 0.3331, 0.0423]], dtype=torch.float64)

In [17]:
b.numpy()

array([[ 0.1197014 ,  0.91228921,  0.44424811],
       [ 0.26773994,  0.72341773,  0.91357858],
       [ 0.24956934,  0.03453914,  0.37598281],
       [ 0.98721395,  0.33306043,  0.04228135]])

In [18]:
b.mul_(2)

tensor([[0.2394, 1.8246, 0.8885],
        [0.5355, 1.4468, 1.8272],
        [0.4991, 0.0691, 0.7520],
        [1.9744, 0.6661, 0.0846]], dtype=torch.float64)

In [19]:
a

array([[ 0.2394028 ,  1.82457842,  0.88849622],
       [ 0.53547989,  1.44683546,  1.82715717],
       [ 0.49913868,  0.06907828,  0.75196562],
       [ 1.9744279 ,  0.66612087,  0.0845627 ]])

Numpy and PyTorch share the same memory space.